### ISSUE TITLE
Upload loop

### ISSUE THREAD

**Issue by alvaroartano** [metaplex-foundation/metaplex#430] opened 2021-09-18 09:50 UTC
![image](https://user-images.githubusercontent.com/28715114/133884759-7b3ba59e-5035-4b31-bc86-597daf83adc4.png)

i get this error when trying to upload

**Comment by jordansexton** [comment] 2021-10-11 23:44
Closing as a duplicate of https://github.com/metaplex-foundation/metaplex/issues/427

**Closed by jordansexton** 2021-10-11 23:44 UTC
