### ISSUE TITLE
Any chance to have a port for Sveltekit ?

### ISSUE THREAD

**Issue by lgs** [metaplex-foundation/metaplex#437] opened 2021-09-19 13:33 UTC
Metaplex project looks grate, but unfortunately React is not a a framework for me and my team to invest in. Is there any chance to have a port for [Sveltekit](https://kit.svelte.dev/)?

**Comment by jordansexton** [comment] 2021-10-11 23:08
Closing this issue as a duplicate of your other issue: https://github.com/metaplex-foundation/metaplex/issues/23

Please don't open multiple issues for the same feature request. If you are interested in implementing this, a separate repo is the way to go.

**Closed by jordansexton** 2021-10-11 23:08 UTC
