### ISSUE TITLE
[Bug]: Candy machine - Transaction was not confirmed (devnet)

### ISSUE THREAD

**Issue by Pcartau** [metaplex-foundation/metaplex#1928] opened 2022-03-09 15:03 UTC
### Which package is this bug report for?

candy machine cli

### Issue description

1 - Follow the tutorial
2 - Configure candy machine with minimal configuration
3 - Use upload command

**I think its highly related to #1919**

solana config get:
`Config File: /Users/XXX/.config/solana/cli/config.yml`
`RPC URL: https://api.devnet.solana.com`
`WebSocket URL: wss://api.devnet.solana.com/ (computed)`
`Keypair Path: /Users/XXX/.config/solana/devnet.json`
`Commitment: confirmed`

config.json
`
{
  "price": 1.0,
  "number": 10,
  "gatekeeper": null,
  "solTreasuryAccount": "XXXXXXXX",
  "splTokenAccount": null,
  "splToken": null,
  "goLiveDate": "",
  "endSettings": null,
  "whitelistMintSettings": null,
  "hiddenSettings": null,
  "storage": "arweave-sol",
  "ipfsInfuraProjectId": null,
  "ipfsInfuraSecret": null,
  "nftStorageKey": null,
  "awsS3Bucket": null,
  "noRetainAuthority": false,
  "noMutable": false
}
`

### Command

```shell
ts-node ~/metaplex/js/packages/cli/src/candy-machine-v2-cli.ts upload -e devnet \
    -k ~/.config/solana/devnet.json \
    -cp config.json \
    -c example \
    ./assets
```

### Relevant log output

```shell
Beginning the upload for 10 (img+json) pairs
started at: 1646837623211
initializing candy machine
No collection set
initialized config for a candy machine with publickey: HJQ1AQg5g1F9txLHKenx5ymmsfZPEbsACwn23zc6NeHH
[0] out of [10] items have been uploaded
Starting upload for [10] items, format {"mediaExt":".png","index":"0"}
Saved bundle upload result to cache.
Computed Bundle range, including 10 file pair(s) totaling 0.218MB.
Processing file groups...
Progress: [████████████████████████████████████████] 100% | 10/10
Uploading bundle via Bundlr... in multiple transactions
0.00008872 SOL to upload 0.289MB with buffer. Sending fund txn...
Successfully funded Arweave Bundler, starting upload
Progress: [████████████████████████████████████████] 100% | 30/30
Bundle uploaded!
Saved bundle upload result to cache.
Upload done. Cleaning up...
Writing all indices in 1 transactions...
Progress: [░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░] 0% | 0/1Translating error Error: Transaction was not confirmed i.
Done. Successful = false.Transaction (/Users/XXX/metaplex/js/node_modules/@solana/web3.js/src/connection.ts:2781:)
ended at: 2022-03-09T14:55:52.021Z. time taken: 00:02:08u/metaplex/js/node_modules/@solana/web3.js/src/util/send-and-)
```

### Operating system

MacOS Big Sur 11.0.1

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment] 2022-03-09 19:04
Duplicate of #1919. Closing.

**Closed by stegaBOB** 2022-03-09 19:04 UTC
Labels: needs tests, bug
