### ISSUE TITLE
Transaction Not Confirmed When Updating Candy Machine

### ISSUE THREAD

**Issue by corybeevers** [metaplex-foundation/metaplex#1625] opened 2022-01-22 16:18 UTC
I am updating Candy Machine date & price in CMV2 and I am getting this:

"Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature HBbfCKKAnihbHVGS579erFytbjeUQLVv1osuu6nRjVprFpo9HHyunFrUh8YPrCeqUH9FeE8aY2ywBeKd6aqFsgS using the Solana Explorer or CLI tools."

Sometimes it is working, but not actually updating the machine, and then the rest of the time it has this transaction error.

I have screenshotted the code when I run the show command and it isn't showing the correct date but everything else is fine.
<img width="1356" alt="Screenshot 2022-01-22 at 16 17 18" src="https://user-images.githubusercontent.com/96397639/150646790-9be6ac94-2a49-4923-b0cc-d44822b09ac3.png">

**Comment by corybeevers** [comment] 2022-01-22 16:29
I have fixed and resolved now :) 

If anyone gets stuck on this though, just comment and it will ping me, I will try and help with the solution I did

**Comment by travzki** [comment] 2022-01-22 19:12
![Screenshot_8](https://user-images.githubusercontent.com/26986388/150652243-0cdf2403-60f8-4dee-9d0e-dc6b3ebf1857.png)
do you know anyting about this error and how to fix ?

**Comment by corybeevers** [comment] 2022-01-24 07:06
It would be easier if you could please copy and paste the code for me to take a look

Have you created and set up your Commandline wallet? Also known as your Keypair

**Comment by justinphan3110** [comment] 2022-01-26 20:31
Hi how did you resolve the Transaction was not confirmed error @corybeevers

**Comment by Khushhal23** [comment] 2022-02-01 06:24
@justinphan3110 That error is because of slowness of solana blockchain, so it depends on the traffic on the blockchain

**Comment by stegaBOB** [comment] 2022-02-04 05:06
Closing this issue. Feel free to ask in our [Discord](https://discord.gg/metaplex) if you still have issues.

**Closed by stegaBOB** 2022-02-04 05:06 UTC
