### ISSUE TITLE
[Bug]: Candy Machine UI didn't Work Properly

### ISSUE THREAD

**Issue by witchkingdom** [metaplex-foundation/metaplex#1974] opened 2022-03-18 08:05 UTC
### Which package is this bug report for?

candy machine ui

### Issue description

The Candy Machine UI is not working properly for whitelistminting at the moment. The wallet holding the SPL Token cannot mint properly. This issue is not happening in the past and also, my setting work well when i am using the other github candy-machine-ui repository. Would you please help to look into the issue? Many thanks 

### Operating system

windows

### Priority this issue should have

Medium (should be fixed soon)

### Check the Docs First

- [X] I have checked the docs and it didn't solve my issue

**Comment by stegaBOB** [comment] 2022-03-20 00:51
Duplicate of #1972.

**Closed by stegaBOB** 2022-03-20 00:51 UTC
Labels: needs tests, bug

**Comment by witchkingdom** [comment] 2022-03-20 02:57
Thank you so much but the issue still cannot be fixed

**Comment by witchkingdom** [comment] 2022-03-20 04:41
More precisely, it can be minted by SPL-token holder now but the phantom wallet cannot fetch the balance for minting.

**Comment by witchkingdom** [comment] 2022-03-20 08:22
Dear Sammy

Thanks. It can be minted properly now but the phantom wallet can’t fetch
the balance while minting.

I have refreshed many times but the problem still exist
