### ISSUE TITLE
mainnet-beta ERROR - Translating error Error: Transaction was not confirmed in 60.01 

### ISSUE THREAD

**Issue by aosagula** [metaplex-foundation/metaplex#1179] opened 2021-12-10 17:12 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

Im running on mainnet-beta the upload of a directory, with only two files this operation is falling constantly, 

This is the error. The transaction is not atomic, every time  has a Cost. 

Translating error Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 3Njay9ySdwxuuCSKLwof6NM8JYWAVVNbsmf7DEffRsrrrjWdKvyFNdi8EEDu5G4dfaXCCqqEcbijMhoUu57L79mD using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
Error deploying config to Solana network. Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 3Njay9ySdwxuuCSKLwof6NM8JYWAVVNbsmf7DEffRsrrrjWdKvyFNdi8EEDu5G4dfaXCCqqEcbijMhoUu57L79mD using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
(node:17352) UnhandledPromiseRejectionWarning: Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature 3Njay9ySdwxuuCSKLwof6NM8JYWAVVNbsmf7DEffRsrrrjWdKvyFNdi8EEDu5G4dfaXCCqqEcbijMhoUu57L79mD using the Solana Explorer or CLI tools.
    at Connection.confirmTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\connection.ts:2602:13)
    at async sendAndConfirmRawTransaction (C:\Users\User\skullcoolnft\metaplex\js\node_modules\@solana\web3.js\src\util\send-and-confirm-raw-transaction.ts:33:5)
    at async Provider.send (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\provider.ts:114:18)
    at async Object.rpc [as initializeConfig] (C:\Users\User\skullcoolnft\metaplex\js\packages\cli\node_modules\@project-serum\anchor\src\program\namespace\rpc.ts:19:23)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:17352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:17352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by MohammadisTired** [comment] 2022-01-12 20:54
Experiencing this issue as well

**Comment by dwarkesh8** [comment] 2022-01-19 03:58
In devnet it is working fine but when switch to mainnet-beta I'm having the same problem !!

**Comment by kelvin2180** [comment] 2022-01-20 13:49
+1

**Comment by hkirat** [comment] 2022-01-22 19:12
+1

**Comment by hkirat** [comment] 2022-01-22 19:48
Try increasing the timeout here - https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/accounts.ts#L583
```js

 const solConnection = new anchor.web3.Connection(
    //@ts-ignore
    customRpcUrl || getCluster(env),
    {
      confirmTransactionInitialTimeout:  60 * 10 * 1000
    }
  );
```

**Comment by Arashi-H** [comment] 2022-02-11 22:20
I have the same issue too. I was trying to upload 1000 (img+json) pairs and got "Translating error Error: Transaction was not confirmed in 60.01 seconds.".
No cache file and only one thing changed is that about 1.6 SOL has transferred.
I didn't have experienced this kind of bug within devnet.

**Comment by Arashi-H** [comment] 2022-02-11 22:30
If someone knows how to withdraw rent fee from account on solana please let me know.

**Comment by NathRyuzaki** [comment] 2022-02-24 06:54
any solution for this problem?

**Comment by Arashi-H** [comment] 2022-02-24 16:23
Thanks for your reply. I've solved this problem with the help of updated metaplex version.

**Comment by 1trackprojects1** [comment] 2022-03-05 16:34
I'm getting same error in devnet though with the latest stable version

**Comment by Lukaris** [comment] 2022-03-05 20:42
> I'm getting same error in devnet though with the latest stable version

yes, me too, in devnet

**Comment by alizhan1** [comment] 2022-03-05 21:35
ye, I am also experiencing same problem for 2 days already :(

**Comment by aosagula** [comment] 2022-03-05 22:14
Plese backup your current mataplex (local version) and get the last version with git.

Be sure that u have the last version of metaplex.
Some time this is the problem.
When i created this issue the network was broken. After that the upload works fine.

Regards

**Comment by stegaBOB** [comment] 2022-03-06 06:02
For those on mainnet, just keep trying and/or use a different RPC. Timeout errors are not things we can fix on our end. As for devnet, the latest solana validator release on devnet (1.9.9) is causing some issues with devnet for the CMv2 program. Only solution is just to wait for the network to not be unstable for devnet.

**Closed by stegaBOB** 2022-03-06 06:02 UTC

**Comment by Michaelhrom23** [comment] 2022-03-06 20:31
> For those on mainnet, just keep trying and/or use a different RPC. Timeout errors are not things we can fix on our end. As for devnet, the latest solana validator release on devnet (1.9.9) is causing some issues with devnet for the CMv2 program. Only solution is just to wait for the network to not be unstable for devnet.

When do you think this bug will be fixed?

**Comment by EzanAsif** [comment] 2022-03-07 06:09
I was having the same issue on devnet but it worked on the third time I executed the same command after 5 minutes.

**Comment by afterworktw** [comment] 2022-03-07 13:06
I got this problem too, even on devnet.

**Comment by Endrave** [comment] 2022-03-07 14:21
Not looking good , i tried across devnet, testnet and mainnet, none working. Also i am not quite sure how RPC work, i just know place the URL for RPC in the command will do, but where to find the RPC URL?

**Comment by aaaasmile** [comment] 2022-03-07 20:53
I tried just now and it works for me on the devnet.

**Comment by Jjfern96** [comment] 2022-03-08 03:02
I'm having this issue on devnet.

**Comment by runlecturesit** [comment] 2022-03-08 09:10
Not working on devnet. Anyone has any suggestions on what to do next?

**Comment by numisman** [comment] 2022-03-08 17:07
> If someone knows how to withdraw rent fee from account on solana please let me know.

Can you use the withdraw command?  ```npx ts-node candy-machine-v2-cli.js withdraw --help```

**Comment by numisman** [comment] 2022-03-08 17:08
Make sure you're done with the CM as that will drain it and close the rent account

**Comment by numisman** [comment] 2022-03-08 17:08
> 

This timeout param is no longer here.

**Comment by numisman** [comment] 2022-03-08 17:43
> From our discord:
> 
> Hey @ everyone! Just wanted to give an update regarding Candy Machine on Devnet. As you may know, there has been some complications with the Candy Machine program on Devnet for the past few days which has resulted in many Transaction was not confirmed in 60.01 seconds errors. This is a complication with the network itself. As a result of this, the Solana Labs team has delayed the v1.9.9 Solana release on Mainnet Beta, and we are working closely with the Solana Labs team to get this resolved ASAP. We will be sure to update you in this channel once this has been resolved.

OH THANK GAWD!

**Comment by mcfriend99** [comment] 2022-04-17 21:24
Anyone ever found a solution to this issue??

**Comment by tskazinski** [comment] 2022-04-18 02:30
I'm experiencing this issue now as well.

**Comment by jocruz** [comment] 2022-04-18 05:06
I am experiencing this as well now after going through every configuration possible, and it also does not return all of my sol, so if I had 2 sol it returns 1.9 sol. Is there a fee that we pay for attempting to run/rent a candy machine?

**Comment by mcfriend99** [comment] 2022-04-19 00:11
I found that the easiest solution is to modify the `confirmTransactionInitialTimeout` option of a `Connection` object and set the timeout to 70 seconds and above. This performed well even when the network was very terrible.

**Comment by jocruz** [comment] 2022-04-19 04:30
> I found that the easiest solution is to modify the `confirmTransactionInitialTimeout` option of a `Connection` object and set the timeout to 70 seconds and above. This performed well even when the network was very terrible.

Thank you for replying I will edit this on future projects!

**Comment by Jjfern96** [comment] 2022-04-19 17:35
> > I found that the easiest solution is to modify the `confirmTransactionInitialTimeout` option of a `Connection` object and set the timeout to 70 seconds and above. This performed well even when the network was very terrible.
> 
> Thank you for replying I will edit this on future projects!

I tried to find this variable but I couldn’t. Is there a way to reset this value by running a command in the terminal window?

**Comment by mcfriend99** [comment] 2022-04-19 18:19
As for resetting, I have no idea. But using the Connection object from web3, the option is available as an argument to the commitment option (it's an Object) which is the second argument to the Connection constructor. Would have loved to show code, but I'm on my phone.

**Comment by joysiriban** [comment] 2022-05-27 19:35
> Try increasing the timeout here - https://github.com/metaplex-foundation/metaplex/blob/master/js/packages/cli/src/helpers/accounts.ts#L583
> 
> ```js
>  const solConnection = new anchor.web3.Connection(
>     //@ts-ignore
>     customRpcUrl || getCluster(env),
>     {
>       confirmTransactionInitialTimeout:  60 * 10 * 1000
>     }
>   );
> ```

Where can I find this? It's not in accounts.ts

**Comment by Arhamirfan** [comment] 2022-05-27 20:00
> Thanks for your reply. I've solved this problem with the help of updated metaplex version.

@Helix-bitnami I am facing the same issue, and lost around 3-4 sol. I am using updated metaplex version. Can you tell how can i get sol back.

**Comment by Arhamirfan** [comment] 2022-05-27 20:13
I was trying to upload collection of 999 (img+json) pairs 8gb of size and got "Translating error Error: Transaction was not confirmed in 60.01 seconds.".
I got no issue on devnet and when i tried mainnet-beta and tried different RPC i got same errors
And because of trying different RPC I lost around 4 SOL.

Kindly let me know how to get the rent back.

**Comment by ogdemster** [comment] 2022-05-28 14:22
we cant get sol back after this error?

**Comment by javildesign** [comment] 2022-05-28 16:20
> I was trying to upload collection of 999 (img+json) pairs 8gb of size and got "Translating error Error: Transaction was not confirmed in 60.01 seconds.". I got no issue on devnet and when i tried mainnet-beta and tried different RPC i got same errors And because of trying different RPC I lost around 4 SOL.
> 
> Kindly let me know how to get the rent back and which RPC should i use with no issues like that.

Hi, you can get your rent back with the command:
npx ts-node ./metaplex/js/packages/cli/src/candy-machine-v2-cli.ts withdraw_all -e mainnet-beta -k ./nft/yourkey.json

**Comment by Arhamirfan** [comment] 2022-05-28 17:08
Thanks @javildesign , it worked.

**Comment by ogdemster** [comment] 2022-05-28 19:20
> I found that the easiest solution is to modify the `confirmTransactionInitialTimeout` option of a `Connection` object and set the timeout to 70 seconds and above. This performed well even when the network was very terrible.

how.

**Comment by Arhamirfan** [comment] 2022-05-28 19:24
@ogdemster we can change the time which is in the constant.tsx or constant.js, the correct location is like: metaplex/js/packages/cli/constants.tsx i guess or maybe inside another folder. You can see the timeout variable there which will be set to 3000, i changed that to 9000 and didn't get any error. You can try that and let me know.
